default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: startup-template_development

test:
  <<: *default
  database: startup-template_test

production:
  <<: *default
  database: startup-template_production
